### ISSUE TITLE
adding a contact us page 

### ISSUE THREAD

**Issue by HaRrY37649** [anuragverma108/WildGuard#333]
A contact us page where user using his email and contact the website admin about any concern they have with the website or any issue related to the content of the website.

**Comment by HaRrY37649** [comment]
bro just open ur on request

**Comment by Chetan-KK** [comment]
Hi @HaRrY37649, for contacting which email id should i use where all mails will come?

**Comment by Shimanshu23** [comment]
By email access I mean is that u need a further feature that uses tha detail stored(which u can access using the get element check the contact html code)and send a email of confirmation or assurance about there review to them

Since I didn't have that I just provide a output message below about receiving tha message

**Comment by Chetan-KK** [comment]
Hi @Shimanshu23 i've used formsubmit api for now
