### ISSUE TITLE
Create a Login and Register Page

### ISSUE THREAD

**Issue by Ashutowsh** [anuragverma108/WildGuard#864]
**Creating a Login and Register Page via username and email address.**

**Comment by SnehaghoshBarsha444** [comment]
Hello Sir,
I am eager to add login and register page to the website.
Can you please assign this issue to me under Hacktoberfest label?
Thank you

**Comment by akash70629** [comment]
@SnehaghoshBarsha444 @Ashutowsh guys, Just a heads up - I've also been assigned to this issue 😂 . I've already created a pull request and am awaiting merge.

As a reminder, Please search for existing issues before opening new ones to avoid duplicates.
Since this issue is already open elsewhere, I'll close this duplicate to keep our issue tracker organized.


Issue #775
PR #863

**Comment by Ashutowsh** [comment]
Sure
